gText_AcceptLetter_CongratulationsPlayer::
	.string "Congratulations, {PLAYER}!\n\nWe are pleased to inform you that your \napplication to the YCombinator Kickstart Grant \n(powered by {STR_VAR_1}) has been accepted. \n\nOur mission is to find the best and \nbrightest young Pokémon Trainers and \nhelp accelerate their careers.$"

gText_AcceptLetter_CongratulationsPlayer2::
	.string "Congratulations, {PLAYER}, you’ve\n"
	.string "been selected!$"

gText_AcceptLetter_WeArePleased::
	.string "We are pleased to inform you that your\n"
	.string "application to the YC Kickstart Grant\l"
	.string "(powered by {STR_VAR_1}) has been\l"
	.string "accepted. Our mission is to find the\l"
	.string "best and brightest young Pokémon\l"
	.string "Trainers and help accelerate their\l"
	.string "careers.$"

gText_AcceptLetter_AsAKickstart::
	.string "As a YC Kickstart Grant recipient, you\n"
	.string "will$"

gText_AcceptLetter_BeFlownTo::
	.string "- Be flown to the SanFran region in\n"
	.string "September.$"

gText_AcceptLetter_ParticipateInTheFirst::
	.string "- Participate in the first season of\n"
	.string "the NEW YC Sanctioned Pokémon League!$"

gText_AcceptLetter_RecieveAllTheBenefits::
	.string "- Receive all the benefits of joining\n"
	.string "the YC family, including housing, a\l"
	.string "stipend, and a toolkit of the best swag\l"
	.string "around.$"

gText_AcceptLetter_PleaseSignTheAttached::
	.string "Please sign the attached documents\n"
	.string "and mail them to YC Headquarters by\l"
	.string "April 17, 2019, to finalize your\l"
	.string "acceptance.$"

gText_AcceptLetter_WereStoked::
	.string "We’re stoked to see what you can do!$"

gText_AcceptLetter_Sincerely::
	.string "Sincerely,$"

gText_AcceptLetter_TheYCFamily::
	.string "The YC Family$"
