LetsFixThis_HideObjectHouse_Script::
	setflag FLAG_TEMP_1
	return


LetsFixThis_EliteVideo_Dialogue::
	return


LetsFixThis_EliteVideo_Dialogue_Text_0:
	.string "You have a new text.$"

gText_LetsFixThis_PeopleOf::
	.string "People of Psfregion1, your Elite Four\n"
	.string "has returned! We could not continue to\l"
	.string "stand by and watch these corporations\l"
	.string "destroy our home for profits.$"

gText_LetsFixThis_WeWillBeGiving::
	.string "We will be giving our full support and\n"
	.string "efforts to assisting Psfgoodteam in\l"
	.string "their mission to help the people of\l"
	.string "this region, alongside Champion\l"
	.string "{PLAYER} and our hometown hero,\l"
	.string "Psfnativerival.$"

gText_LetsFixThis_WePrayTheGovernment::
	.string "We pray the government of Psfregion1\n"
	.string "will open their eyes to the damage\l"
	.string "these companies have done…$"

gText_LetsFixThis_ButWeWillNot::
	.string "…but we will not sit quietly and wait for\n"
	.string "salvation to come to us! We must join\l"
	.string "together to save ourselves and fight\l"
	.string "to restore the glory of Psfregion1!$"

gText_LetsFixThis_OhLooksLike::
	.string "Oh, looks like we all got the same\n"
	.string "message… It's from the Psfgoodteam\l"
	.string "Event Bot.$"

gText_LetsFixThis_ComeCelebrate::
	.string "“Come celebrate the return of the Elite\n"
	.string "Four! Tonight, in the Psfcity9 Packing\l"
	.string "District. Follow the music to the\l"
	.string "center warehouse!”$"

gText_LetsFixThis_SoundsLikeIt::
	.string "Sounds like it could be fun. You going\n"
	.string "to go?$"

gText_LetsFixThis_IMightGoALittle::
	.string "I might go a little later. I don’t love\n"
	.string "warehouse raves, but this is a special\l"
	.string "occasion, you know? The other reason\l"
	.string "I’m here is actually to tell you\l"
	.string "Psfgoodadmin new initiatives.$"

gText_LetsFixThis_WhatreThey::
	.string "What’re they up to?$"

gText_LetsFixThis_TheyWantAllHands::
	.string "They want all hands on deck at\n"
	.string "Psfcave7. We’re converting it into a new\l"
	.string "base, and there’s gonna be a big meeting\l"
	.string "to talk about next steps.$"

gText_LetsFixThis_GuessIShould::
	.string "Guess I should go to that, right?$"

gText_LetsFixThis_ActuallyGivenHowMuch::
	.string "Actually, given how much work there is\n"
	.string "to get done, I don’t think it matters\l"
	.string "what you do first. I already said I’d\l"
	.string "head to Psfcave7. Either way, I’ll see\l"
	.string "you later?$"
