Manhunt_TowerObjectSetUp_Script::
	setobjectxy 2, 8, 6
	setobjectxyperm 2, 8, 6
	setobjectmovementtype 2, MOVEMENT_TYPE_FACE_UP
	return


Manhunt_HideObject_Script::
	setflag FLAG_TEMP_1
	return


Manhunt_Assignment_Dialogue::
	addvar VAR_RUSTURF_TUNNEL_STATE, 1
	return


Manhunt_Cherie_Battle_Script::
	return


Manhunt_Teodoro_Battle_Script::
	return


Manhunt_Dudley_Battle_Script::
	return


Manhunt_Encounter_Psfgoodboss_Dialogue::
	return

