#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_PsfTownsAndRoutes
#define MAP_PSFCITY8   (0 | (0 << 8))
#define MAP_PSFROUTE17 (1 | (0 << 8))
#define MAP_PSFCITYY16 (2 | (0 << 8))
#define MAP_PSFROUTE11 (3 | (0 << 8))
#define MAP_PSFROUTE21 (4 | (0 << 8))
#define MAP_PSFCITY7   (5 | (0 << 8))
#define MAP_PSFROUTE22 (6 | (0 << 8))
#define MAP_PSFCITY15  (7 | (0 << 8))
#define MAP_PSFCITY6   (8 | (0 << 8))
#define MAP_PSFROUTE9  (9 | (0 << 8))
#define MAP_PSFCITY12  (10 | (0 << 8))
#define MAP_PSFROUTE38 (11 | (0 << 8))
#define MAP_PSFROUTE70 (12 | (0 << 8))
#define MAP_PSFROUTE19 (13 | (0 << 8))
#define MAP_PSFROUTE8  (14 | (0 << 8))
#define MAP_PSFROUTE30 (15 | (0 << 8))
#define MAP_PSFROUTE14 (16 | (0 << 8))
#define MAP_PSFCITY13  (17 | (0 << 8))
#define MAP_PSFCITY14  (18 | (0 << 8))
#define MAP_PSFPLACE7  (19 | (0 << 8))
#define MAP_PSFPLACE11 (20 | (0 << 8))
#define MAP_PSFPLACE13 (21 | (0 << 8))
#define MAP_PSFROUTE1  (22 | (0 << 8))
#define MAP_PSFCITY17  (23 | (0 << 8))
#define MAP_PSFPLACE16 (24 | (0 << 8))
#define MAP_PSFROUTE72 (25 | (0 << 8))
#define MAP_PSFROUTE12 (26 | (0 << 8))
#define MAP_PSFCITY9   (27 | (0 << 8))
#define MAP_PSFROUTE63 (28 | (0 << 8))
#define MAP_PSFCITY11  (29 | (0 << 8))
#define MAP_PSFCAVE7   (30 | (0 << 8))
#define MAP_PSFPLACE9  (31 | (0 << 8))
#define MAP_PSFCITY3   (32 | (0 << 8))
#define MAP_PSFROUTE49 (33 | (0 << 8))
#define MAP_PSFCITY4   (34 | (0 << 8))
#define MAP_PSFROUTE5  (35 | (0 << 8))
#define MAP_PSFROUTE7  (36 | (0 << 8))
#define MAP_PSFCITY2   (37 | (0 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (1 << 8))
#define MAP_SLATEPORT_CITY      (1 | (1 << 8))
#define MAP_MAUVILLE_CITY       (2 | (1 << 8))
#define MAP_RUSTBORO_CITY       (3 | (1 << 8))
#define MAP_FORTREE_CITY        (4 | (1 << 8))
#define MAP_LILYCOVE_CITY       (5 | (1 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (1 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (1 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (1 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (1 << 8))
#define MAP_OLDALE_TOWN         (10 | (1 << 8))
#define MAP_DEWFORD_TOWN        (11 | (1 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (1 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (1 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (1 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (1 << 8))
#define MAP_ROUTE101            (16 | (1 << 8))
#define MAP_ROUTE102            (17 | (1 << 8))
#define MAP_ROUTE103            (18 | (1 << 8))
#define MAP_ROUTE104            (19 | (1 << 8))
#define MAP_ROUTE105            (20 | (1 << 8))
#define MAP_ROUTE106            (21 | (1 << 8))
#define MAP_ROUTE107            (22 | (1 << 8))
#define MAP_ROUTE108            (23 | (1 << 8))
#define MAP_ROUTE109            (24 | (1 << 8))
#define MAP_ROUTE110            (25 | (1 << 8))
#define MAP_ROUTE111            (26 | (1 << 8))
#define MAP_ROUTE112            (27 | (1 << 8))
#define MAP_ROUTE113            (28 | (1 << 8))
#define MAP_ROUTE114            (29 | (1 << 8))
#define MAP_ROUTE115            (30 | (1 << 8))
#define MAP_ROUTE116            (31 | (1 << 8))
#define MAP_ROUTE117            (32 | (1 << 8))
#define MAP_ROUTE118            (33 | (1 << 8))
#define MAP_ROUTE119            (34 | (1 << 8))
#define MAP_ROUTE120            (35 | (1 << 8))
#define MAP_ROUTE121            (36 | (1 << 8))
#define MAP_ROUTE122            (37 | (1 << 8))
#define MAP_ROUTE123            (38 | (1 << 8))
#define MAP_ROUTE124            (39 | (1 << 8))
#define MAP_ROUTE125            (40 | (1 << 8))
#define MAP_ROUTE126            (41 | (1 << 8))
#define MAP_ROUTE127            (42 | (1 << 8))
#define MAP_ROUTE128            (43 | (1 << 8))
#define MAP_ROUTE129            (44 | (1 << 8))
#define MAP_ROUTE130            (45 | (1 << 8))
#define MAP_ROUTE131            (46 | (1 << 8))
#define MAP_ROUTE132            (47 | (1 << 8))
#define MAP_ROUTE133            (48 | (1 << 8))
#define MAP_ROUTE134            (49 | (1 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (1 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (1 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (1 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (1 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (1 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (1 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (1 << 8))

// gMapGroup_IndoorPsfcity8
#define MAP_PSFCITY8_COMPOUND_1F       (0 | (2 << 8))
#define MAP_PSFCITY8_COMPOUND_2F       (1 | (2 << 8))
#define MAP_PSFCITY8_POKEMON_CENTER_1F (2 | (2 << 8))

// gMapGroup_IndoorPsfcity15
#define MAP_PSFCITY15_GYM (0 | (3 << 8))

// gMapGroup_IndoorPsfcity6
#define MAP_PSFCITY6_GYM (0 | (4 << 8))

// gMapGroup_IndoorPsfcity14
#define MAP_PSFCITY14_GYM (0 | (5 << 8))

// gMapGroup_IndoorPsfcity11
#define MAP_PSFCITY11_GYM             (0 | (6 << 8))
#define MAP_PSFCITY11_BREEDING_CENTER (1 | (6 << 8))

// gMapGroup_IndoorPsfplace9
#define MAP_PSFPLACE9_ROOF (0 | (7 << 8))

// gMapGroup_IndoorPsfcity3
#define MAP_PSFCITY3_MANSION (0 | (8 << 8))
#define MAP_PSFCITY2_GYM     (1 | (8 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (9 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (9 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (9 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (9 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (9 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (10 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (10 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (10 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (10 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (10 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (11 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (11 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (11 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (11 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (11 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (11 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (12 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (12 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (12 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (12 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (12 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (12 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (12 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (13 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (13 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (13 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (13 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (13 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (13 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (13 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (13 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (14 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (14 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (14 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (14 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (14 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (14 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (14 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (14 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (14 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (15 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (15 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (15 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (15 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (15 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (15 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (15 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (16 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (16 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (16 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (16 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (16 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (16 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (16 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (17 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (17 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (17 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (17 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (17 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (17 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (17 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (17 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (17 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (17 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (17 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (17 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (17 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (17 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (18 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (18 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (18 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (18 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (18 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (18 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (18 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (18 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (19 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (19 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (19 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (19 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (19 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (19 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (19 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (19 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (19 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (19 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (19 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (19 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (19 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (19 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (19 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (19 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (19 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (20 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (20 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (20 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (20 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (20 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (20 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (20 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (20 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (20 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (20 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (21 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (21 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (21 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (21 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (21 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (21 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (21 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (21 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (21 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (21 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (21 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (21 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (21 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (21 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (21 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (21 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (21 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (21 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (21 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (21 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (21 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (21 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (21 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (22 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (22 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (22 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (22 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (22 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (22 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (22 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (22 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (22 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (22 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (22 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (22 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (22 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (23 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (23 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (24 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (24 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (25 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (25 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (26 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (26 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (27 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (27 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (28 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (28 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (28 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (29 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (30 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (31 << 8))

// gMapGroup_Dungeons
#define MAP_PSFBADGUY1TOWER_1F                       (0 | (32 << 8))
#define MAP_PSFBADGUY1TOWER_2F                       (1 | (32 << 8))
#define MAP_PSFBADGUY1TOWER_5F                       (2 | (32 << 8))
#define MAP_PSFBADGUY1TOWER_7F                       (3 | (32 << 8))
#define MAP_PSFBADGUY1TOWER_10F                      (4 | (32 << 8))
#define MAP_PSFBADGUY1TOWER_11F                      (5 | (32 << 8))
#define MAP_PSFBADGUY1TOWER_ELEVATOR                 (6 | (32 << 8))
#define MAP_METEOR_FALLS_1F_1R                       (7 | (32 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (8 | (32 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (9 | (32 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (10 | (32 << 8))
#define MAP_RUSTURF_TUNNEL                           (11 | (32 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (12 | (32 << 8))
#define MAP_DESERT_RUINS                             (13 | (32 << 8))
#define MAP_GRANITE_CAVE_1F                          (14 | (32 << 8))
#define MAP_GRANITE_CAVE_B1F                         (15 | (32 << 8))
#define MAP_GRANITE_CAVE_B2F                         (16 | (32 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (17 | (32 << 8))
#define MAP_PETALBURG_WOODS                          (18 | (32 << 8))
#define MAP_MT_CHIMNEY                               (19 | (32 << 8))
#define MAP_JAGGED_PASS                              (20 | (32 << 8))
#define MAP_FIERY_PATH                               (21 | (32 << 8))
#define MAP_MT_PYRE_1F                               (22 | (32 << 8))
#define MAP_MT_PYRE_2F                               (23 | (32 << 8))
#define MAP_MT_PYRE_3F                               (24 | (32 << 8))
#define MAP_MT_PYRE_4F                               (25 | (32 << 8))
#define MAP_MT_PYRE_5F                               (26 | (32 << 8))
#define MAP_MT_PYRE_6F                               (27 | (32 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (28 | (32 << 8))
#define MAP_MT_PYRE_SUMMIT                           (29 | (32 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (30 | (32 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (31 | (32 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (32 | (32 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (33 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (34 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (35 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (36 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (37 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (38 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (39 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (40 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (41 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (42 | (32 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (43 | (32 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (44 | (32 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (45 | (32 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (46 | (32 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (47 | (32 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (48 | (32 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (49 | (32 << 8))
#define MAP_VICTORY_ROAD_1F                          (50 | (32 << 8))
#define MAP_VICTORY_ROAD_B1F                         (51 | (32 << 8))
#define MAP_VICTORY_ROAD_B2F                         (52 | (32 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (53 | (32 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (54 | (32 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (55 | (32 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (56 | (32 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (57 | (32 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (58 | (32 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (59 | (32 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (60 | (32 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (61 | (32 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (62 | (32 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (63 | (32 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (64 | (32 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (65 | (32 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (66 | (32 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (67 | (32 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (68 | (32 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (69 | (32 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (70 | (32 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (71 | (32 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (72 | (32 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (73 | (32 << 8))
#define MAP_ISLAND_CAVE                              (74 | (32 << 8))
#define MAP_ANCIENT_TOMB                             (75 | (32 << 8))
#define MAP_UNDERWATER_ROUTE134                      (76 | (32 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (77 | (32 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (78 | (32 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (79 | (32 << 8))
#define MAP_SCORCHED_SLAB                            (80 | (32 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (81 | (32 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (82 | (32 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (83 | (32 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (84 | (32 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (85 | (32 << 8))
#define MAP_SKY_PILLAR_1F                            (86 | (32 << 8))
#define MAP_SKY_PILLAR_2F                            (87 | (32 << 8))
#define MAP_SKY_PILLAR_3F                            (88 | (32 << 8))
#define MAP_SKY_PILLAR_4F                            (89 | (32 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (90 | (32 << 8))
#define MAP_SKY_PILLAR_5F                            (91 | (32 << 8))
#define MAP_SKY_PILLAR_TOP                           (92 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (93 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (94 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (95 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (96 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (97 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (98 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (99 | (32 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (100 | (32 << 8))
#define MAP_MIRAGE_TOWER_1F                          (101 | (32 << 8))
#define MAP_MIRAGE_TOWER_2F                          (102 | (32 << 8))
#define MAP_MIRAGE_TOWER_3F                          (103 | (32 << 8))
#define MAP_MIRAGE_TOWER_4F                          (104 | (32 << 8))
#define MAP_DESERT_UNDERPASS                         (105 | (32 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (106 | (32 << 8))
#define MAP_ARTISAN_CAVE_1F                          (107 | (32 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (108 | (32 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (109 | (32 << 8))
#define MAP_MARINE_CAVE_END                          (110 | (32 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (111 | (32 << 8))
#define MAP_TERRA_CAVE_END                           (112 | (32 << 8))
#define MAP_ALTERING_CAVE                            (113 | (32 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (114 | (32 << 8))
#define MAP_PSFCAVE9                                 (115 | (32 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (33 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (33 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (33 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (33 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (33 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (33 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (33 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (33 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (33 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (33 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (33 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (33 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (33 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (33 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (33 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (33 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (33 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (33 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (33 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (33 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (33 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (33 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (33 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (33 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (33 << 8))
#define MAP_TRADE_CENTER             (25 | (33 << 8))
#define MAP_RECORD_CORNER            (26 | (33 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (33 << 8))
#define MAP_CONTEST_HALL             (28 | (33 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (33 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (33 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (33 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (33 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (33 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (33 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (33 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (33 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (33 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (33 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (33 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (33 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (33 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (33 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (33 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (33 << 8))
#define MAP_UNION_ROOM               (60 | (33 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (34 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (34 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (34 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (34 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (34 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (34 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (34 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (34 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (34 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (34 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (34 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (34 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (34 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (34 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (34 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (34 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (34 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (34 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (34 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (34 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (34 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (34 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (34 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (34 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (34 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (34 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (34 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (34 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (34 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (34 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (34 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (34 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (34 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (34 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (34 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (34 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (34 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (34 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (34 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (34 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (34 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (34 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (34 << 8))
#define MAP_BLACK_MAP                                       (89 | (34 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (35 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (35 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (36 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (37 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (37 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (37 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (37 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (38 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (39 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (40 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (40 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (40 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (41 << 8))

#define MAP_GROUPS_COUNT 42

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
