#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_PsfTownsAndRoutes
#define MAP_SOUTHBAY                          (0 | (0 << 8))
#define MAP_PSFROUTE17                        (1 | (0 << 8))
#define MAP_BERNALHEIGHTS                     (2 | (0 << 8))
#define MAP_PSFROUTE11                        (3 | (0 << 8))
#define MAP_PSFROUTE21                        (4 | (0 << 8))
#define MAP_DOGPATCH                          (5 | (0 << 8))
#define MAP_PSFROUTE22                        (6 | (0 << 8))
#define MAP_SOMA                              (7 | (0 << 8))
#define MAP_MISSION                           (8 | (0 << 8))
#define MAP_PSFROUTE9                         (9 | (0 << 8))
#define MAP_TENDERLOIN                        (10 | (0 << 8))
#define MAP_PSFROUTE38                        (11 | (0 << 8))
#define MAP_PSFROUTE70                        (12 | (0 << 8))
#define MAP_PSFROUTE19                        (13 | (0 << 8))
#define MAP_PSFROUTE8                         (14 | (0 << 8))
#define MAP_PSFROUTE30                        (15 | (0 << 8))
#define MAP_PSFROUTE14                        (16 | (0 << 8))
#define MAP_CHINATOWN                         (17 | (0 << 8))
#define MAP_JAPANTOWN                         (18 | (0 << 8))
#define MAP_LOMBARDSTREET                     (19 | (0 << 8))
#define MAP_FERRYBUILDING                     (20 | (0 << 8))
#define MAP_FISHERMANSWHARF                   (21 | (0 << 8))
#define MAP_PSFROUTE1                         (22 | (0 << 8))
#define MAP_ALAMEDA                           (23 | (0 << 8))
#define MAP_OAKLANDFERRY                      (24 | (0 << 8))
#define MAP_PSFROUTE72                        (25 | (0 << 8))
#define MAP_PSFROUTE12                        (26 | (0 << 8))
#define MAP_OAKLAND                           (27 | (0 << 8))
#define MAP_PSFROUTE63                        (28 | (0 << 8))
#define MAP_BERKELEY                          (29 | (0 << 8))
#define MAP_ALCATRAZ                          (30 | (0 << 8))
#define MAP_FORTPOINT                         (31 | (0 << 8))
#define MAP_PRESIDIO                          (32 | (0 << 8))
#define MAP_PSFROUTE49                        (33 | (0 << 8))
#define MAP_PACIFICA                          (34 | (0 << 8))
#define MAP_PSFROUTE5                         (35 | (0 << 8))
#define MAP_PSFROUTE7                         (36 | (0 << 8))
#define MAP_GLDNGTEPARK                       (37 | (0 << 8))
#define MAP_HAIGHTASHBURY                     (38 | (0 << 8))
#define MAP_PSFROUTE43                        (39 | (0 << 8))
#define MAP_PAINTEDLADIES                     (40 | (0 << 8))
#define MAP_PSFROUTE13                        (41 | (0 << 8))
#define MAP_CASTRO                            (42 | (0 << 8))
#define MAP_CASTRO_GYM                        (43 | (0 << 8))
#define MAP_GLDNGTEBRIDGE                     (44 | (0 << 8))
#define MAP_ROBINWILLTUNNEL                   (45 | (0 << 8))
#define MAP_MARIN                             (46 | (0 << 8))
#define MAP_PSFROUTE61                        (47 | (0 << 8))
#define MAP_MUIRWOODS                         (48 | (0 << 8))
#define MAP_ROBINWILLTUNNEL_B1F               (49 | (0 << 8))
#define MAP_MUIRWOODS_INNER                   (50 | (0 << 8))
#define MAP_ROBINWILLTUNNEL_B2F               (51 | (0 << 8))
#define MAP_NAVALBASE                         (52 | (0 << 8))
#define MAP_CHASECENTER_ENTRANCE              (53 | (0 << 8))
#define MAP_CHASECENTER_LOCKERS               (54 | (0 << 8))
#define MAP_CHASECENTER_SKYBOX                (55 | (0 << 8))
#define MAP_CHASECENTER_ARENA                 (56 | (0 << 8))
#define MAP_CHASECENTER_STANDS                (57 | (0 << 8))
#define MAP_PRESIDIO_COMPOUND_1F              (58 | (0 << 8))
#define MAP_TREASUREISLAND                    (59 | (0 << 8))
#define MAP_TREASUREISLAND_RESTAURANT         (60 | (0 << 8))
#define MAP_ALCATRAZ_B1F                      (61 | (0 << 8))
#define MAP_ALCATRAZ_B2F                      (62 | (0 << 8))
#define MAP_CASTRO_BALL_SHOP                  (63 | (0 << 8))
#define MAP_PSFROUTE62                        (64 | (0 << 8))
#define MAP_LAKEMERRITT                       (65 | (0 << 8))
#define MAP_PSFROUTE18                        (66 | (0 << 8))
#define MAP_TWINPEAKS                         (67 | (0 << 8))
#define MAP_OKAY_LETS_FIXIT_FLASHBACK         (68 | (0 << 8))
#define MAP_SUNSET                            (69 | (0 << 8))
#define MAP_SUNSET_APARTMENT                  (70 | (0 << 8))
#define MAP_TENDERLOIN_LIBRARY                (71 | (0 << 8))
#define MAP_MARIN_ELITE_HOME                  (72 | (0 << 8))
#define MAP_ALAMEDA_ARCHER_HOUSE              (73 | (0 << 8))
#define MAP_OAKLAND_WAREHOUSE                 (74 | (0 << 8))
#define MAP_LAYOUT_TESTER                     (75 | (0 << 8))
#define MAP_ALAMEDA_POST_EARTHQUAKE           (76 | (0 << 8))
#define MAP_PSFROUTE25                        (77 | (0 << 8))
#define MAP_UNDERGROUNDLAB                    (78 | (0 << 8))
#define MAP_SUNSET_SABRINA_HOUSE              (79 | (0 << 8))
#define MAP_WE_CAN_STOP_YOU_ACTUALLY_CUTSCENE (80 | (0 << 8))
#define MAP_PRESIDIO_HAUNTEDHOUSE             (81 | (0 << 8))
#define MAP_CHINATOWN_RACISTHOUSE             (82 | (0 << 8))
#define MAP_CHINATOWN_TUNNEL                  (83 | (0 << 8))
#define MAP_PACIFICA_GEMHOUSE                 (84 | (0 << 8))
#define MAP_TENDERLOIN_TROLLEY_HQ             (85 | (0 << 8))
#define MAP_MARIN_SOLAR                       (86 | (0 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (1 << 8))
#define MAP_SLATEPORT_CITY      (1 | (1 << 8))
#define MAP_MAUVILLE_CITY       (2 | (1 << 8))
#define MAP_RUSTBORO_CITY       (3 | (1 << 8))
#define MAP_FORTREE_CITY        (4 | (1 << 8))
#define MAP_LILYCOVE_CITY       (5 | (1 << 8))
#define MAP_MOSSDEEP_CITY       (6 | (1 << 8))
#define MAP_SOOTOPOLIS_CITY     (7 | (1 << 8))
#define MAP_EVER_GRANDE_CITY    (8 | (1 << 8))
#define MAP_LITTLEROOT_TOWN     (9 | (1 << 8))
#define MAP_OLDALE_TOWN         (10 | (1 << 8))
#define MAP_DEWFORD_TOWN        (11 | (1 << 8))
#define MAP_LAVARIDGE_TOWN      (12 | (1 << 8))
#define MAP_FALLARBOR_TOWN      (13 | (1 << 8))
#define MAP_VERDANTURF_TOWN     (14 | (1 << 8))
#define MAP_PACIFIDLOG_TOWN     (15 | (1 << 8))
#define MAP_ROUTE101            (16 | (1 << 8))
#define MAP_ROUTE102            (17 | (1 << 8))
#define MAP_ROUTE103            (18 | (1 << 8))
#define MAP_ROUTE104            (19 | (1 << 8))
#define MAP_ROUTE105            (20 | (1 << 8))
#define MAP_ROUTE106            (21 | (1 << 8))
#define MAP_ROUTE107            (22 | (1 << 8))
#define MAP_ROUTE108            (23 | (1 << 8))
#define MAP_ROUTE109            (24 | (1 << 8))
#define MAP_ROUTE110            (25 | (1 << 8))
#define MAP_ROUTE111            (26 | (1 << 8))
#define MAP_ROUTE112            (27 | (1 << 8))
#define MAP_ROUTE113            (28 | (1 << 8))
#define MAP_ROUTE114            (29 | (1 << 8))
#define MAP_ROUTE115            (30 | (1 << 8))
#define MAP_ROUTE116            (31 | (1 << 8))
#define MAP_ROUTE117            (32 | (1 << 8))
#define MAP_ROUTE118            (33 | (1 << 8))
#define MAP_ROUTE119            (34 | (1 << 8))
#define MAP_ROUTE120            (35 | (1 << 8))
#define MAP_ROUTE121            (36 | (1 << 8))
#define MAP_ROUTE122            (37 | (1 << 8))
#define MAP_ROUTE123            (38 | (1 << 8))
#define MAP_ROUTE124            (39 | (1 << 8))
#define MAP_ROUTE125            (40 | (1 << 8))
#define MAP_ROUTE126            (41 | (1 << 8))
#define MAP_ROUTE127            (42 | (1 << 8))
#define MAP_ROUTE128            (43 | (1 << 8))
#define MAP_ROUTE129            (44 | (1 << 8))
#define MAP_ROUTE130            (45 | (1 << 8))
#define MAP_ROUTE131            (46 | (1 << 8))
#define MAP_ROUTE132            (47 | (1 << 8))
#define MAP_ROUTE133            (48 | (1 << 8))
#define MAP_ROUTE134            (49 | (1 << 8))
#define MAP_UNDERWATER_ROUTE124 (50 | (1 << 8))
#define MAP_UNDERWATER_ROUTE126 (51 | (1 << 8))
#define MAP_UNDERWATER_ROUTE127 (52 | (1 << 8))
#define MAP_UNDERWATER_ROUTE128 (53 | (1 << 8))
#define MAP_UNDERWATER_ROUTE129 (54 | (1 << 8))
#define MAP_UNDERWATER_ROUTE105 (55 | (1 << 8))
#define MAP_UNDERWATER_ROUTE125 (56 | (1 << 8))

// gMapGroup_IndoorSouthbay
#define MAP_SOUTHBAY_COMPOUND_1F       (0 | (2 << 8))
#define MAP_SOUTHBAY_COMPOUND_2F       (1 | (2 << 8))
#define MAP_SOUTHBAY_POKEMON_CENTER_1F (2 | (2 << 8))

// gMapGroup_IndoorSOMA
#define MAP_SOMA_GYM       (0 | (3 << 8))
#define MAP_SOMA_NEWSPAPER (1 | (3 << 8))

// gMapGroup_IndoorMission
#define MAP_MISSION_GYM        (0 | (4 << 8))
#define MAP_MISSION_CONSULTING (1 | (4 << 8))

// gMapGroup_IndoorJapantown
#define MAP_JAPANTOWN_GYM        (0 | (5 << 8))
#define MAP_JAPANTOWN_RAMEN      (1 | (5 << 8))
#define MAP_JAPANTOWN_BALLS      (2 | (5 << 8))
#define MAP_JAPANTOWN_MUSICVENUE (3 | (5 << 8))

// gMapGroup_IndoorBerkeley
#define MAP_BERKELEY_GYM             (0 | (6 << 8))
#define MAP_BERKELEY_BREEDING_CENTER (1 | (6 << 8))
#define MAP_BERKELEY_ICE_CREAM_SHOP  (2 | (6 << 8))

// gMapGroup_IndoorFortpoint
#define MAP_FORTPOINT_ROOF (0 | (7 << 8))

// gMapGroup_IndoorPresidio
#define MAP_PRESIDIO_MANSION (0 | (8 << 8))
#define MAP_GLDNGTEPARK_GYM  (1 | (8 << 8))

// gMapGroup_IndoorHaightashbury
#define MAP_HAIGHTASHBURY_GYM (0 | (9 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (10 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (10 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (10 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (10 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (10 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (11 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (11 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (11 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (11 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (11 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1            (0 | (12 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (1 | (12 << 8))
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (2 | (12 << 8))
#define MAP_DEWFORD_TOWN_GYM               (3 | (12 << 8))
#define MAP_DEWFORD_TOWN_HALL              (4 | (12 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2            (5 | (12 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (13 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (13 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (13 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (13 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (13 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (13 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (13 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (14 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (14 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (14 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (14 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (14 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (14 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (14 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (14 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (15 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (15 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (15 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (15 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (15 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (15 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (15 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (15 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (15 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (16 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (16 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (16 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (16 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (16 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (16 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (16 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (17 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (17 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (17 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (17 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (17 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (17 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (17 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (18 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (18 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (18 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (18 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (18 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (18 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (18 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (18 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (18 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (18 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (18 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (18 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (18 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (18 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM               (0 | (19 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (19 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (19 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (19 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (19 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (19 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (19 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (19 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (20 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (20 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (20 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (20 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (20 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (20 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (20 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (20 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (20 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (20 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (20 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (20 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (20 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (20 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (20 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (20 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (20 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1            (0 | (21 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (21 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (21 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (21 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (21 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (21 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (21 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (21 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (21 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (21 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (22 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (22 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (22 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (22 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (22 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (22 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (22 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (22 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (22 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (22 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (22 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (22 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (22 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (22 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (22 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (22 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (22 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (22 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (22 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (22 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (22 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (22 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (22 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM               (0 | (23 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (23 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (23 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (23 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (23 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (23 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (23 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (23 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (23 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (23 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (23 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (23 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (23 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (24 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (24 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (25 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (25 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (26 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (26 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (27 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (27 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (28 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (28 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (29 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (29 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (29 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (30 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (31 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (32 << 8))

// gMapGroup_Dungeons
#define MAP_SALESFORCETOWER_1F                       (0 | (33 << 8))
#define MAP_SALESFORCETOWER_2F                       (1 | (33 << 8))
#define MAP_SALESFORCETOWER_3F                       (2 | (33 << 8))
#define MAP_SALESFORCETOWER_4F                       (3 | (33 << 8))
#define MAP_SALESFORCETOWER_5F                       (4 | (33 << 8))
#define MAP_SALESFORCETOWER_6F                       (5 | (33 << 8))
#define MAP_SALESFORCETOWER_7F                       (6 | (33 << 8))
#define MAP_SALESFORCETOWER_8F                       (7 | (33 << 8))
#define MAP_SALESFORCETOWER_9F                       (8 | (33 << 8))
#define MAP_SALESFORCETOWER_10F                      (9 | (33 << 8))
#define MAP_SALESFORCETOWER_11F                      (10 | (33 << 8))
#define MAP_SALESFORCETOWER_ELEVATOR                 (11 | (33 << 8))
#define MAP_METEOR_FALLS_1F_1R                       (12 | (33 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (13 | (33 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (14 | (33 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (15 | (33 << 8))
#define MAP_RUSTURF_TUNNEL                           (16 | (33 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (17 | (33 << 8))
#define MAP_DESERT_RUINS                             (18 | (33 << 8))
#define MAP_GRANITE_CAVE_1F                          (19 | (33 << 8))
#define MAP_GRANITE_CAVE_B1F                         (20 | (33 << 8))
#define MAP_GRANITE_CAVE_B2F                         (21 | (33 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (22 | (33 << 8))
#define MAP_PETALBURG_WOODS                          (23 | (33 << 8))
#define MAP_MT_CHIMNEY                               (24 | (33 << 8))
#define MAP_JAGGED_PASS                              (25 | (33 << 8))
#define MAP_FIERY_PATH                               (26 | (33 << 8))
#define MAP_MT_PYRE_1F                               (27 | (33 << 8))
#define MAP_MT_PYRE_2F                               (28 | (33 << 8))
#define MAP_MT_PYRE_3F                               (29 | (33 << 8))
#define MAP_MT_PYRE_4F                               (30 | (33 << 8))
#define MAP_MT_PYRE_5F                               (31 | (33 << 8))
#define MAP_MT_PYRE_6F                               (32 | (33 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (33 | (33 << 8))
#define MAP_MT_PYRE_SUMMIT                           (34 | (33 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (35 | (33 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (36 | (33 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (37 | (33 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (38 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (39 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (40 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (41 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (42 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (43 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (44 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (45 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (46 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (47 | (33 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (48 | (33 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (49 | (33 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (50 | (33 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (51 | (33 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (52 | (33 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (53 | (33 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (54 | (33 << 8))
#define MAP_VICTORY_ROAD_1F                          (55 | (33 << 8))
#define MAP_VICTORY_ROAD_B1F                         (56 | (33 << 8))
#define MAP_VICTORY_ROAD_B2F                         (57 | (33 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (58 | (33 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (59 | (33 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (60 | (33 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (61 | (33 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (62 | (33 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (63 | (33 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE                    (64 | (33 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                      (65 | (33 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (66 | (33 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (67 | (33 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (68 | (33 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (69 | (33 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (70 | (33 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (71 | (33 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (72 | (33 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (73 | (33 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (74 | (33 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (75 | (33 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (76 | (33 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (77 | (33 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (78 | (33 << 8))
#define MAP_ISLAND_CAVE                              (79 | (33 << 8))
#define MAP_ANCIENT_TOMB                             (80 | (33 << 8))
#define MAP_UNDERWATER_ROUTE134                      (81 | (33 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (82 | (33 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (83 | (33 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (84 | (33 << 8))
#define MAP_SCORCHED_SLAB                            (85 | (33 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (86 | (33 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (87 | (33 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (88 | (33 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                      (89 | (33 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                       (90 | (33 << 8))
#define MAP_SKY_PILLAR_1F                            (91 | (33 << 8))
#define MAP_SKY_PILLAR_2F                            (92 | (33 << 8))
#define MAP_SKY_PILLAR_3F                            (93 | (33 << 8))
#define MAP_SKY_PILLAR_4F                            (94 | (33 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (95 | (33 << 8))
#define MAP_SKY_PILLAR_5F                            (96 | (33 << 8))
#define MAP_SKY_PILLAR_TOP                           (97 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (98 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (99 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (100 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (101 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (102 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (103 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (104 | (33 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (105 | (33 << 8))
#define MAP_MIRAGE_TOWER_1F                          (106 | (33 << 8))
#define MAP_MIRAGE_TOWER_2F                          (107 | (33 << 8))
#define MAP_MIRAGE_TOWER_3F                          (108 | (33 << 8))
#define MAP_MIRAGE_TOWER_4F                          (109 | (33 << 8))
#define MAP_DESERT_UNDERPASS                         (110 | (33 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (111 | (33 << 8))
#define MAP_ARTISAN_CAVE_1F                          (112 | (33 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (113 | (33 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (114 | (33 << 8))
#define MAP_MARINE_CAVE_END                          (115 | (33 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (116 | (33 << 8))
#define MAP_TERRA_CAVE_END                           (117 | (33 << 8))
#define MAP_ALTERING_CAVE                            (118 | (33 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (119 | (33 << 8))
#define MAP_GLDNGTEWILDS                             (120 | (33 << 8))
#define MAP_CHASECENTER_CONSTRUCTION                 (121 | (33 << 8))
#define MAP_GLDNGTEWILDS_SPRING                      (122 | (33 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (34 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (34 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (34 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (34 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (34 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (34 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (34 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (34 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (34 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (34 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (34 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (34 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (34 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (34 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (34 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (34 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (34 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (34 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (34 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (34 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (34 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (34 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (34 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (34 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (34 << 8))
#define MAP_TRADE_CENTER             (25 | (34 << 8))
#define MAP_RECORD_CORNER            (26 | (34 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (34 << 8))
#define MAP_CONTEST_HALL             (28 | (34 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (34 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (34 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (34 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (34 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (34 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (34 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (34 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (34 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (34 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (34 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (34 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (34 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (34 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (34 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (34 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (34 << 8))
#define MAP_UNION_ROOM               (60 | (34 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (35 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (35 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (35 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (35 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (35 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (35 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (35 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (35 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (35 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (35 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (35 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (35 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (35 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (35 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (35 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (35 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (35 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (35 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (35 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (35 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (35 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (35 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (35 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (35 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (35 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (35 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (35 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (35 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (35 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (35 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (35 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (35 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (35 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (35 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (35 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (35 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (35 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (35 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (35 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (35 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (35 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (35 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (35 << 8))
#define MAP_BLACK_MAP                                       (89 | (35 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (36 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (36 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (37 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (38 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (38 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (38 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (38 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (39 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (40 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (41 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (41 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (41 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (42 << 8))

#define MAP_GROUPS_COUNT 43

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
