#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

#define MUGSHOT_HILDA 3
#define MUGSHOT_MARSHAL 60
#define MUGSHOT_SABRINA 71

//SPEAKER
#define SPEAKER_DEFAULT             0
#define SPEAKER_JASMINE             1
#define SPEAKER_GRUNT               2
#define SPEAKER_BLAINE              3
#define SPEAKER_BROCK               4
#define SPEAKER_BRUNO               5
#define SPEAKER_BUG_CATCHER         6
#define SPEAKER_BUGSY               7
#define SPEAKER_CHUCK               8
#define SPEAKER_CLAIR               9
#define SPEAKER_ELM                 10
#define SPEAKER_ERIKA               11
#define SPEAKER_FALKNER             12
#define SPEAKER_FISHERMAN           13
#define SPEAKER_GIOVANNI            14
#define SPEAKER_GIRL                15
#define SPEAKER_GREEN               16
#define SPEAKER_JANINE              17
#define SPEAKER_KAREN               18
#define SPEAKER_KID                 19
#define SPEAKER_KOGA                20
#define SPEAKER_KURT                21
#define SPEAKER_LANCE               22
#define SPEAKER_LT_SURGE            23
#define SPEAKER_MAN                 24
#define SPEAKER_MISTY               25
#define SPEAKER_MORTY               26
#define SPEAKER_OLD_MAN             27
#define SPEAKER_OLD_WOMAN           28
#define SPEAKER_POLICEMAN           29
#define SPEAKER_PRYCE               30
#define SPEAKER_RED                 31
#define SPEAKER_ROCKET_GRUNT_MALE   32
#define SPEAKER_ROCKET_GRUNT_FEMALE 33
#define SPEAKER_SABRINA             34
#define SPEAKER_SILVER              35
#define SPEAKER_STEVEN              36
#define SPEAKER_SWIMMER_MALE        37
#define SPEAKER_WHITNEY             38
#define SPEAKER_WILL                39
#define SPEAKER_WOMAN               40
#define SPEAKER_YOUNGSTER           41
#define SPEAKER_FIREBREATHER        42
#define SPEAKER_BEAUTY              43
#define SPEAKER_BIRD_KEEPER         44
#define SPEAKER_BLACK_BELT          45
#define SPEAKER_EUSINE              46
#define SPEAKER_WAITER              47
#define SPEAKER_PROTON              48
#define SPEAKER_PETREL              49
#define SPEAKER_ARIANA              50
#define SPEAKER_ARCHER              51
#define SPEAKER_COLLECTOR           52
#define SPEAKER_BILL                53
#define SPEAKER_BOARDER             54
#define SPEAKER_JUGGLER             55
#define SPEAKER_KIMONO_GIRL         56
#define SPEAKER_LASS                57
#define SPEAKER_MEDIUM              58
#define SPEAKER_MEDIUM_2            59
#define SPEAKER_POKE_MANIAC         60
#define SPEAKER_SAGE                61
#define SPEAKER_SUPER_NERD          62
#define SPEAKER_ACE_TRAINER_M       63
#define SPEAKER_ACE_TRAINER_F       64
#define SPEAKER_LI                  65
#define SPEAKER_AROMA_LADY          66
#define SPEAKER_BATTLE_GIRL         67
#define SPEAKER_MOM                 68
#define NUM_SPEAKERS 99999

//Tail
#define TAIL_DEFAULT 0
#define TAIL_WHISPER 1
#define TAIL_SHOUT 2
#define TAIL_THOUGHT 3
#define TAIL_TALK 4

//Emotions
#define EMOTE_DEFAULT 0
#define EMOTE_ANGRY 1
#define EMOTE_SAD 2
#define EMOTE_HAPPY 3
#define EMOTE_LAUGH 4
#define EMOTE_SWEAT 5
#define EMOTE_SHOCK 6
#define EMOTE_CONFUSE 7
#define EMOTE_LOVE 8

//Phone
#define PHONE_OFF 0
#define PHONE_ON 1

//PSF names
#define SPEAKER_NEWS                69
#define SPEAKER_ZOEY                70
#define SPEAKER_BIANCA              71
#define SPEAKER_BART                72
#define SPEAKER_MARKETING_STAFF     73
#define SPEAKER_ANNOUNCER           74
#define SPEAKER_MALVA               75
#define SPEAKER_CROWD_A             76
#define SPEAKER_CROWD_B             77
#define SPEAKER_CROWD_C             78
#define SPEAKER_CROWD_D             79
#define SPEAKER_RUPERT              80
#define SPEAKER_OAK                 81
#define SPEAKER_RESIDENT_A          82
#define SPEAKER_RESIDENT_B          83
#define SPEAKER_RESIDENT_C          84
#define SPEAKER_RESIDENT_D          85
#define SPEAKER_SIARL               86
#define SPEAKER_SIEBOLD             87
#define SPEAKER_DAGMAR              88
#define SPEAKER_GURL                89
#define SPEAKER_LEAGUE_STAFF_A      90
#define SPEAKER_ROCKET_MEMBER_A     91
#define SPEAKER_ROCKET_MEMBER_B     92
#define SPEAKER_DAVID               93
#define SPEAKER_ISHAN               94
#define SPEAKER_ROSE                95
#define SPEAKER_PROTEST_A           96
#define SPEAKER_PROTEST_B           97
#define SPEAKER_PROTEST_C           98
#define SPEAKER_PROTEST_D           99
#define SPEAKER_VITOMIR             100
#define SPEAKER_RABIA               101
#define SPEAKER_LANDLORD            102
#define SPEAKER_JULIUS              103
#define SPEAKER_MADISON             104
#define SPEAKER_STRANDED_A          105
#define SPEAKER_STRANDED_B          106
#define SPEAKER_RESIDENT_E          107
#define SPEAKER_RESIDENT_F          108
#define SPEAKER_DRASNA              109
#define SPEAKER_WIKSTROM            110
#define SPEAKER_ALEKSANDER          111
#define SPEAKER_SUMMER              112
#define SPEAKER_MAID                113
#define SPEAKER_NEWS_B              114
#define SPEAKER_ARNAV               115
#define SPEAKER_OLIVER              116
#define SPEAKER_CHIEF               118
#define SPEAKER_CILAN               119
#define SPEAKER_LENORA              120
#define SPEAKER_DOOR                121
#define SPEAKER_TEODORO             122
#define SPEAKER_DUDLEY              123
#define SPEAKER_CHERIE              124
#define SPEAKER_MATTHEW             125
#define SPEAKER_FANNY               126
#define SPEAKER_CRAIG               127
#define SPEAKER_ANTONE              128
#define SPEAKER_ORI                 129
#define SPEAKER_HIKO                130
#define SPEAKER_POLICE              131
#define SPEAKER_MACK                132
#define SPEAKER_TYZONN              133
#define SPEAKER_WILL2               134
#define SPEAKER_RONNY               135
#define SPEAKER_DAX                 136
#define SPEAKER_BRENNAN             137
#define SPEAKER_ATTENDANT           138
#define SPEAKER_SPEAKER             139
#define SPEAKER_GHOST               140
#define SPEAKER_ISMAIL              141
#define SPEAKER_STAN_SOMA           142
#define SPEAKER_STAN_SOMAB          143
#define SPEAKER_STAN_SOMAC          144
#define SPEAKER_STAN_SOMAD          145
#define SPEAKER_STAN_SOMAE          146
#define SPEAKER_SERGEY              147
#define SPEAKER_REPORTER            148
#define SPEAKER_TROLLEY_GUY         149
#define SPEAKER_HESTER              150
#define SPEAKER_YCOMBINATOR_STAFF   151
#define SPEAKER_TONALLI             152
#define SPEAKER_DRUMMER_B           153
#define SPEAKER_DRUMMER_C           154
#define SPEAKER_DRUMMER_D           155
#define SPEAKER_LIIDIA              156
#define SPEAKER_RAINER              157
#define SPEAKER_BRONSON             158
#define SPEAKER_SHASHI              159
#define SPEAKER_LEAH                160
#define SPEAKER_GUARD               161
#define SPEAKER_SHOPKEEPER          162
#define SPEAKER_ELIOR               163
#define SPEAKER_LELAND              164
#define SPEAKER_AMBROGIO            165
#define SPEAKER_JORIS               166
#define SPEAKER_NURSE               167
#define SPEAKER_AUGUSTE             168
#define SPEAKER_JULIA               169
#define SPEAKER_ALICE               170
#define SPEAKER_FERRAN              171
#define SPEAKER_ANTHONY             172
#define SPEAKER_SEVENSISTERS_TINA		173
#define SPEAKER_SEVENSISTERS_PAUL		174
#define SPEAKER_SEVENSISTERS_JON		175
#define SPEAKER_SEVENSISTERS_BRADLEY	176
#define SPEAKER_SEVENSISTERS_JO			177
#define SPEAKER_SEVENSISTERS_HANNAH		178
#define SPEAKER_SEVENSISTERS_RACHEL		179
#define SPEAKER_KATHARINA               180
#define SPEAKER_OFFICIANT               181
#define SPEAKER_HELEN                   182
#define SPEAKER_RUSTY                   183
#define SPEAKER_WILLOW                  184
#define SPEAKER_GRIFF                   185
#define SPEAKER_LUNA                    186
#define SPEAKER_MAX                     187
#define SPEAKER_BLAZE                   188
#define SPEAKER_KIKI                    189
#define SPEAKER_EJ                      190
#define SPEAKER_WAITE                   191
#define SPEAKER_DEBRA                   192
#define SPEAKER_WALDRON                 193
#define SPEAKER_ISIDORE                 194
#define SPEAKER_FILIP                   195
#define SPEAKER_GERTRUDE                196
#define SPEAKER_KHALEEL                 197
#define SPEAKER_AUGUSTA                 198
#define SPEAKER_NANCY                   199
#define SPEAKER_PANNEN                  200
#define SPEAKER_MADRONE                 201
#define SPEAKER_TWITTER_CEO             202
#define SPEAKER_AMAZON_CEO              203
#define SPEAKER_UBER_DRIVER1            204
#define SPEAKER_UBER_DRIVER2            205
#define SPEAKER_UBER_DRIVER3            206
#define SPEAKER_PERSUASIVE_LANDLORD     207
#define SPEAKER_PERSUASIVE_SIBLING      208
#define SPEAKER_UBER_GRUNT1             209
#define SPEAKER_UBER_GRUNT2             210
#define SPEAKER_UBER_CEO                211
#define SPEAKER_GYM_ATTENDANT           212

#endif
