#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_DAWN 0
#define MUGSHOT_ETHAN 1
#define MUGSHOT_HILBERT 2
#define MUGSHOT_HILDA 3
#define MUGSHOT_LUCAS 4
#define MUGSHOT_LYRA 5
#define MUGSHOT_NATE 6
#define MUGSHOT_ROSA 7
#define MUGSHOT_AARON 8
#define MUGSHOT_ALDER 9
#define MUGSHOT_ARCHER 10
#define MUGSHOT_ARGENTA 11
#define MUGSHOT_ARIANA 12
#define MUGSHOT_BENGA 13
#define MUGSHOT_BERTHA 14
#define MUGSHOT_BIANCA 15
#define MUGSHOT_BLAINE 16
#define MUGSHOT_BROCK 17
#define MUGSHOT_BRUNO 18
#define MUGSHOT_BRYCEN 19
#define MUGSHOT_BUGSY 20
#define MUGSHOT_BURGH 21
#define MUGSHOT_BYRON 22
#define MUGSHOT_CAITLIN 23
#define MUGSHOT_CANDICE 24
#define MUGSHOT_CHEREN 25
#define MUGSHOT_CHEREN_2 26
#define MUGSHOT_CHILI 27
#define MUGSHOT_CHUCK 28
#define MUGSHOT_CILAN 29
#define MUGSHOT_CLAIR 30
#define MUGSHOT_CLAY 31
#define MUGSHOT_COLRESS 32
#define MUGSHOT_CRASHER_WAKE 33
#define MUGSHOT_CRESS 34
#define MUGSHOT_CYNTHIA 35
#define MUGSHOT_DAHLIA 36
#define MUGSHOT_DARACH 37
#define MUGSHOT_DRAYDEN 38
#define MUGSHOT_ELESA 39
#define MUGSHOT_ELESA_2 40
#define MUGSHOT_ERIKA 41
#define MUGSHOT_FALKNER 42
#define MUGSHOT_FANTINA 43
#define MUGSHOT_FLINT 44
#define MUGSHOT_GARDENIA 45
#define MUGSHOT_GHETSIS 46
#define MUGSHOT_GHETSIS_2 47
#define MUGSHOT_GIOVANNI 48
#define MUGSHOT_GRIMSLEY 49
#define MUGSHOT_HUGH 50
#define MUGSHOT_IRIS 51
#define MUGSHOT_JANINE 52
#define MUGSHOT_JASMINE 53
#define MUGSHOT_KAREN 54
#define MUGSHOT_LANCE 55
#define MUGSHOT_LENORA 56
#define MUGSHOT_LT_SURGE 57
#define MUGSHOT_LUCIAN 58
#define MUGSHOT_MARLON 59
#define MUGSHOT_MARSHAL 60
#define MUGSHOT_MAYLENE 61
#define MUGSHOT_MISTY 62
#define MUGSHOT_MORTY 63
#define MUGSHOT_N 64
#define MUGSHOT_PALMER 65
#define MUGSHOT_PETREL 66
#define MUGSHOT_PROTON 67
#define MUGSHOT_PRYCE 68
#define MUGSHOT_ROARK 69
#define MUGSHOT_ROXIE 70
#define MUGSHOT_SABRINA 71
#define MUGSHOT_SHAUNTAL 72
#define MUGSHOT_SILVER 73
#define MUGSHOT_SKYLA 74
#define MUGSHOT_THORTON 75
#define MUGSHOT_VOLKNER 76
#define MUGSHOT_WHITNEY 77
#define MUGSHOT_TEST 78

#define MSGBOX_TEST 0

//SPEAKER
#define SPEAKER_DEFAULT 0
#define SPEAKER_JASMINE 1

//Tail
#define TAIL_DEFAULT 0
#define TAIL_WHISPER 1
#define TAIL_SHOUT 2
#define TAIL_THOUGHT 3
#define TAIL_TALK 4

//Emotions
#define EMOTE_DEFAULT 0
#define EMOTE_ANGRY 1
#define EMOTE_SAD 2
#define EMOTE_HAPPY 3
#define EMOTE_LAUGH 4
#define EMOTE_SWEAT 5
#define EMOTE_SHOCK 6
#define EMOTE_CONFUSE 7
#define EMOTE_LOVE 8

//Phone
#define PHONE_OFF 0
#define PHONE_ON 1

//https://www.pokecommunity.com/showpost.php?p=10345947&postcount=252
#endif
