#ifndef GUARD_CONSTANTS_QUESTS_H
#define GUARD_CONSTANTS_QUESTS_H

//questmenu scripting command params
#define QUEST_MENU_OPEN                 0   //opens the quest menu (questId = 0)
#define QUEST_MENU_UNLOCK_QUEST         1   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_SET_ACTIVE           2   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_SET_REWARD           3   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_COMPLETE_QUEST       4   //questId = QUEST_X (0-indexed)
#define QUEST_MENU_CHECK_UNLOCKED       5   //checks if questId has been unlocked. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_ACTIVE         6   //checks if questId has been unlocked. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_REWARD         7  //checks if questId is in Reward state. Returns result to gSpecialVar_Result
#define QUEST_MENU_CHECK_COMPLETE       8   //checks if questId has been completed. Returns result to gSpecialVar_Result
#define QUEST_MENU_BUFFER_QUEST_NAME    9   //buffers a quest name to gStringVar1
#define QUEST_MENU_CHECK_INACTIVE       10

// quest number defines
#define QUEST_PLAYERSADVENTURE 0
#define QUEST_RETURNDOLL          1
#define QUEST_BRINGFRUIT    2
#define QUEST_BRINGFIRETYPE  3
#define QUEST_STOPMUGGING   4
#define QUEST_STOLENTRADE   5
#define QUEST_HAUNTABUILDING	6
#define QUEST_SOCIALMEDIA	7
#define QUEST_CONSOLATIONPRIZE	8
#define QUEST_RIGHTINGWRONGS	9
#define QUEST_ENTERTHEDRAGON	10
#define QUEST_BREAKTHEINTERNET	11
#define QUEST_SHUTDOWNMEDICINEMAN	12
#define QUEST_BUILDINGSCOPE	13
#define QUEST_NOGOODDEED	14
#define QUEST_IMPROVBATTLING	15
#define QUEST_IMPROVBATTLINGCHAMPIONSHIP	16
#define QUEST_INSTALLNATUREPROBES	17
#define QUEST_MANOFMANYHATS	18
#define QUEST_RECRUITLOCALARTISTS	19
#define QUEST_RESTAURANTEXPANSION1	20
#define QUEST_RESTAURANTEXPANSION2	21
#define QUEST_RESTAURANTEXPANSION3	22
#define QUEST_CULTURALPURITY	23
#define QUEST_HYBRIDCULTURE	24
#define QUEST_ALOHAFROMALOLA	25
#define QUEST_BUILDINGANEXHIBIT	26
#define QUEST_UNKNOWNMORTYQUESTA	27
#define QUEST_UNKNOWNMORTYQUESTB	28
#define QUEST_UNKNOWNCHUCKQUESTA	29
#define QUEST_UNKNOWNCHUCKQUESTB	30
#define QUEST_BIOMERESEARCH	31
#define QUEST_BERRYSUSTAINABILITY	32
#define QUEST_THEONLYHEADSHOPINTOWN	33
#define QUEST_INVERSEHALLUCINOGENIC	34
#define QUEST_UNKNOWNCLAIRQUESTA	35
#define QUEST_UNKNOWNCLAIRQUESTB	36
#define QUEST_CONTRACTORPORYGON	37
#define QUEST_ANGELDELIVERY	38
#define QUEST_GETTHEBANDBACKTOGETHER	39
#define QUEST_FOODTRUCKBUREACRACY	40
#define QUEST_DETECTIVEARIANA	41
#define QUEST_UNKNOWNBRUCELEEQUEST	42
#define QUEST_CHALLENGEOFTHE7SISTERS	43
#define QUEST_ESPORTS	44
#define QUEST_CUTEPOKEMON	45
#define QUEST_WALLACEARMY	46
#define QUEST_DEXCOMPLETION	47
#define QUEST_CABLECARDANCING	48
#define QUEST_KITCHENVOLUNTEERING	49
#define QUEST_ARTISANBALLS1	50
#define QUEST_ARTISANBALLS2	51
#define QUEST_ARTISANBALLS3	52
#define QUEST_SHELTERSWITCHEROO	53
#define QUEST_SHELTERTAXISOLUTION	54
#define QUEST_LASTMUSICVENUEINSANFRANCISCO	55
#define QUEST_GARDENCLEANUP	56
#define QUEST_GARDENCLEANUPADVANCED	57
#define QUEST_EMPLOYEDEVERAFTER	58
#define QUEST_BUTONLYINMYBACKYARD	59
#define QUEST_NEIGHBORHOODCLEANUP	60
#define QUEST_NEIGHBORHOODCLEANUP2	61
#define QUEST_NEIGHBORHOODCLEANUP3	62
#define QUEST_NEIGHBORHOODCLEANUP4	63
#define QUEST_ROCKCOLLECTOR	64
#define QUEST_HANG20	65
#define QUEST_ALLTHATGLITTERSMIGHTBEGOLD	66
#define QUEST_UNKNOWNFISHINGQUEST	67
#define QUEST_HIDDENGROTTOMAPPING	68
#define QUEST_HIDDENGROTTOMAPPING2	69
#define QUEST_ULTRAWORMHOLERESEARCH	70
#define QUEST_UNKNOWNGOVERNMENTSOCIALMEDIAQUEST	71
#define QUEST_DRUMCIRCLE	72
#define QUEST_UNKNOWNPROP22QUEST	73
#define QUEST_UNKNOWNTIMETRAVELQUEST	74
#define QUEST_UNKNOWNCONSTRUCTIONSTRIKEQUEST	75
#define QUEST_IBELIEVEICANFLY	76
#define QUEST_WILDFIRERISK	77
#define QUEST_THEBOYWHOCRIESWITHWOLVES	78
#define QUEST_UNKNOWNTROLLEYPROBLEM	79
#define QUEST_UNKNOWNLANDFILLQUEST	80
#define QUEST_TAXICABTURNAROUNDSEA	81
#define QUEST_TAXICABTURNAROUNDAIR	82
#define QUEST_TAXICABTURNAROUNDLAND	83
#define QUEST_PERSUASIVEPASSENGER	84
#define QUEST_BODEGABURNOUT	85
#define QUEST_WAREHOUSEWARFARE	86
#define QUEST_RESTORETOTHEIRFORMERGLORY	87

#define QUEST_COUNT (QUEST_RESTORETOTHEIRFORMERGLORY + 1)

#define SUB_QUEST_1          0
#define SUB_QUEST_2          1
#define SUB_QUEST_3          2
#define SUB_QUEST_4          3
#define SUB_QUEST_5          4
#define SUB_QUEST_6          5
#define SUB_QUEST_7          6
#define SUB_QUEST_8          7
#define SUB_QUEST_9          8
#define SUB_QUEST_10         9
#define SUB_QUEST_11        10
#define SUB_QUEST_12        11
#define SUB_QUEST_13        12
#define SUB_QUEST_14        13
#define SUB_QUEST_15        14
#define SUB_QUEST_16        15
#define SUB_QUEST_17        16
#define SUB_QUEST_18        17
#define SUB_QUEST_19        18
#define SUB_QUEST_20        19
#define SUB_QUEST_21        20
#define SUB_QUEST_22        21
#define SUB_QUEST_23        22
#define SUB_QUEST_24        23
#define SUB_QUEST_25        24
#define SUB_QUEST_26        25
#define SUB_QUEST_27        26
#define SUB_QUEST_28        27
#define SUB_QUEST_29        28
#define SUB_QUEST_30        29

#define QUEST_HAUNTABUILDING_SUB_COUNT 6
#define QUEST_SOCIALMEDIA_SUB_COUNT	9
#define QUEST_CONSOLATIONPRIZE_SUB_COUNT	5
#define QUEST_RIGHTINGWRONGS_SUB_COUNT	4
#define QUEST_BREAKTHEINTERNET_SUB_COUNT	3
#define QUEST_IMPROVBATTLING_SUB_COUNT	4
#define QUEST_INSTALLNATUREPROBES_SUB_COUNT	3
#define QUEST_RESTAURANTEXPANSION1_SUB_COUNT	4
#define QUEST_RESTAURANTEXPANSION2_SUB_COUNT	5
#define QUEST_HYBRIDCULTURE_SUB_COUNT	3
#define QUEST_BUILDINGANEXHIBIT_SUB_COUNT	4
#define QUEST_BIOMERESEARCH_SUB_COUNT	8
#define QUEST_BERRYSUSTAINABILITY_SUB_COUNT	6
#define QUEST_CONTRACTORPORYGON_SUB_COUNT	3
#define QUEST_GETTHEBANDBACKTOGETHER_SUB_COUNT	5
#define QUEST_FOODTRUCKBUREACRACY_SUB_COUNT	4
#define QUEST_DETECTIVEARIANA_SUB_COUNT	3
#define QUEST_CHALLENGEOFTHE7SISTERS_SUB_COUNT	7
#define QUEST_CUTEPOKEMON_SUB_COUNT	4
#define QUEST_WALLACEARMY_SUB_COUNT	5
#define QUEST_DEXCOMPLETION_SUB_COUNT	2
#define QUEST_KITCHENVOLUNTEERING_SUB_COUNT	5
#define QUEST_ARTISANBALLS_SUB_COUNT	7
#define QUEST_ARTISANBALLS2_SUB_COUNT	3
#define QUEST_SHELTERSWITCHEROO_SUB_COUNT	5
#define QUEST_SHELTERTAXISOLUTION_SUB_COUNT	5
#define QUEST_NEIGHBORHOODCLEANUP_SUB_COUNT	5
#define QUEST_NEIGHBORHOODCLEANUP2_SUB_COUNT	4
#define QUEST_NEIGHBORHOODCLEANUP3_SUB_COUNT	3
#define QUEST_ROCKCOLLECTOR_SUB_COUNT	10
#define QUEST_HIDDENGROTTOMAPPING_SUB_COUNT	5
#define QUEST_HIDDENGROTTOMAPPING2_SUB_COUNT	3
#define QUEST_ULTRAWORMHOLERESEARCH_SUB_COUNT	10
#define QUEST_WILDFIRERISK_SUB_COUNT	3
#define QUEST_THEBOYWHOCRIESWITHWOLVES_SUB_COUNT	9
#define QUEST_TAXICABTURNAROUNDSEA_SUB_COUNT	5
#define QUEST_TAXICABTURNAROUNDAIR_SUB_COUNT	5
#define QUEST_TAXICABTURNAROUNDLAND_SUB_COUNT	7
#define QUEST_PERSUASIVEPASSENGER_SUB_COUNT	3
#define QUEST_BODEGABURNOUT_SUB_COUNT	17
#define QUEST_WAREHOUSEWARFARE_SUB_COUNT	3
#define QUEST_RESTORETOTHEIRFORMERGLORY_SUB_COUNT	4

#define SUB_QUEST_COUNT (QUEST_HAUNTABUILDING_SUB_COUNT + QUEST_SOCIALMEDIA_SUB_COUNT + QUEST_CONSOLATIONPRIZE_SUB_COUNT + QUEST_RIGHTINGWRONGS_SUB_COUNT + QUEST_BREAKTHEINTERNET_SUB_COUNT + QUEST_IMPROVBATTLING_SUB_COUNT + QUEST_INSTALLNATUREPROBES_SUB_COUNT + QUEST_RESTAURANTEXPANSION1_SUB_COUNT + QUEST_RESTAURANTEXPANSION2_SUB_COUNT + QUEST_HYBRIDCULTURE_SUB_COUNT + QUEST_BUILDINGANEXHIBIT_SUB_COUNT + QUEST_BIOMERESEARCH_SUB_COUNT + QUEST_BERRYSUSTAINABILITY_SUB_COUNT + QUEST_CONTRACTORPORYGON_SUB_COUNT + QUEST_GETTHEBANDBACKTOGETHER_SUB_COUNT + QUEST_FOODTRUCKBUREACRACY_SUB_COUNT + QUEST_DETECTIVEARIANA_SUB_COUNT + QUEST_CHALLENGEOFTHE7SISTERS_SUB_COUNT + QUEST_CUTEPOKEMON_SUB_COUNT + QUEST_WALLACEARMY_SUB_COUNT + QUEST_DEXCOMPLETION_SUB_COUNT + QUEST_KITCHENVOLUNTEERING_SUB_COUNT + QUEST_ARTISANBALLS_SUB_COUNT + QUEST_ARTISANBALLS2_SUB_COUNT + QUEST_SHELTERSWITCHEROO_SUB_COUNT + QUEST_SHELTERTAXISOLUTION_SUB_COUNT + QUEST_NEIGHBORHOODCLEANUP_SUB_COUNT + QUEST_NEIGHBORHOODCLEANUP2_SUB_COUNT + QUEST_NEIGHBORHOODCLEANUP3_SUB_COUNT + QUEST_ROCKCOLLECTOR_SUB_COUNT + QUEST_HIDDENGROTTOMAPPING_SUB_COUNT + QUEST_HIDDENGROTTOMAPPING2_SUB_COUNT + QUEST_ULTRAWORMHOLERESEARCH_SUB_COUNT + QUEST_WILDFIRERISK_SUB_COUNT + QUEST_THEBOYWHOCRIESWITHWOLVES_SUB_COUNT + QUEST_TAXICABTURNAROUNDSEA_SUB_COUNT + QUEST_TAXICABTURNAROUNDAIR_SUB_COUNT + QUEST_TAXICABTURNAROUNDLAND_SUB_COUNT + QUEST_PERSUASIVEPASSENGER_SUB_COUNT + QUEST_BODEGABURNOUT_SUB_COUNT + QUEST_WAREHOUSEWARFARE_SUB_COUNT + QUEST_RESTORETOTHEIRFORMERGLORY_SUB_COUNT)

#define QUEST_ARRAY_COUNT (SUB_QUEST_COUNT > QUEST_COUNT ? SUB_QUEST_COUNT : QUEST_COUNT)
#endif // GUARD_CONSTANTS_QUESTS_H
