//VAR_STORYLINE_STATE

#define STORY_WEST_SANFRAN_COMPLETE     9
#define STORY_FERRY FIXED       10
#define STORY_DEFEAT_ARCHER_ALAMEDA     11
#define STORY_DEFEAT_BERKELEY_PROTEST       12
#define STORY_COMPLETE_ALCATRAZ     14
#define STORY_EAST_SANFRAN_COMPLETE     21
#define STORY_CALLED_TO_CONSTRUCTION        22
#define STORY_DEFEATED_GARBODOR 23
#define STORY_NEED_SLEEP_BEFORE_SIEBOLD 24
#define STORY_ASSIGNED_SIEBOLD_QUESTS 25
#define STORY_COMPLETED_NAVAL_BASE 26
#define STORY_START_CHAMPIONSHIP 27
#define STORY_TOURNAMENT_EXPLAINED 28
#define STORY_BIANCA_WON_GROUP 29
#define STORY_READY_GROUP_STAGE 30
#define STORY_GROUP_STATE_COMPLETE 31
#define STORY_SEMIFINAL_COMPLETE 32
#define STORY_WATCH_SEMIFINAL 33
#define STORY_READY_FINALS 34
#define STORY_SAVED_FINALS 35
#define STORY_WON_FINALS 36
#define STORY_EXPLORE_TREASURE_ISLAND 37
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
#define STORY_
