//VAR_STORYLINE_STATE //0x40FC

#define STORY_WEST_SANFRAN_ONLY         0
#define STORY_WEST_SANFRAN_COMPLETE     9
#define STORY_FERRY_FIXED       10
#define STORY_DEFEAT_ARCHER_ALAMEDA     11
#define STORY_DEFEAT_BERKELEY_PROTEST       12
#define STORY_DEFEAT_MORTY  13
#define STORY_COMPLETE_ALCATRAZ     14
#define STORY_EAST_SANFRAN_COMPLETE     21
#define STORY_CALLED_TO_CONSTRUCTION        22
#define	STORY_DEFEATED_GARBODOR	23
#define	STORY_NEED_SLEEP_BEFORE_SIEBOLD	24
#define	STORY_ASSIGNED_SIEBOLD_QUESTS	25
#define	STORY_COMPLETED_NAVAL_BASE	26
#define	STORY_START_CHAMPIONSHIP 27
#define	STORY_CHAMPIONSHIP_EXPLAINED	28
#define	STORY_BIANCA_WON_GROUP	29
#define	STORY_READY_GROUP_STAGE	30
#define	STORY_GROUP_STATE_COMPLETE	31
#define	STORY_SEMIFINAL_COMPLETE	32
#define	STORY_WATCH_SEMIFINAL	33
#define	STORY_READY_FINALS	34
#define	STORY_SAVE_FINALS	35
#define	STORY_WON_FINALS	36
#define	STORY_EXPLORE_TREASUREISLAND	37
#define	STORY_SAVE_ARCHER_TREASUREISLAND	38
#define	STORY_POST_BATTLE_ARCHER_TREASUREISLAND	39
#define	STORY_ARCHER_EXPLAIN_RESTORATION	40
#define	STORY_RESTORATION_1_COMPLETE	41
#define	STORY_POST_YOU_REALIZE_WERE_EVIL	42
#define	STORY_MORNING_OF_TIMELINE_SPLIT	43
#define	STORY_START_FALSE_TIMELINE	44
#define	STORY_1ST_TEAMROCKET_TAKEDOWN	45
#define	STORY_2ND_TEAMROCKET_TAKEDOWN	46
#define	STORY_3RD_TEAMROCKET_TAKEDOWN	47
#define	STORY_TEAMROCKET_FINISHED	48
#define	STORY_SAVE_DIANTHA	49
#define	STORY_POST_DIANTHA	50
#define	STORY_CONGRATULATED_BY_ROSE	51
#define	STORY_RECIEVED_BAMBOO_STAR	52
#define	STORY_BEGIN_LETS_FIX_IT	53
#define STORY_MORNING_AFTER_TIMETRAVEL 99
#define	STORY_START_TRUE_TIMELINE	100
#define	STORY_DEFEATED_GIOVANNI	101
#define	STORY_RECIVED_RAVE_INVITE	102
#define	STORY_RAVE_OR_SPEECH_COMPLETE	103
#define	STORY_RAVE_AND_SPEECH_COMPLETE	104
#define	STORY_1ST_TAKEDOWN	105
#define	STORY_PRE_EARTHQUAKE	106
#define	STORY_POST_EARTHQUAKE	107
#define	STORY_POST_DYNAMAX_BOSS	108
#define	STORY_BEFORE_SABRINA_BREAKIN	109
#define	STORY_WARP_TILE_ACCESSIBLE	110
#define	STORY_CLEAR  111

//VAR_PLAYER_HOME_STATE 0x4092
#define HAS_NOT_MET_BIANCA  1
#define HAS_MET_BIANCA  2
#define CHECKED_OUT_BEDROOM   3
#define POST_SWAGBAG    4
#define SLEPT_AFTER_SWAGBAG 5
#define OPENED_FASHION_CASE 6
#define FINISHED_1_1    7
#define POST_NAVALBASE_RAID 8
#define NEXT_DAY_CHAMPIONSHIP   9

// VAR_GYM_1_STATE | VAR_GYM_3_STATE | VAR_GYM_4_STATE | VAR_GYM_5-STATE | VAR_GYM_6_STATE | VAR_GYM_7_STATE | VAR_GYM_8_STATE | VAR_GYM_2_STATE
#define GYM_PUZZLE_COMPLETE 1
#define GYM_LEADER_ON_BATTLEFIELD   2
#define GYM_SAVE_BEFORE_LEADER 3
#define GYM_DEFEATED_LEADER 4
#define GYM_EXPLAINED_BADGE_AND_TM  5

//VAR_PSFROUTE9_STATE
#define HAS_NOT_MET_ARCHER  0
#define SAVED_BEFORE_ARCHER_PSFROUTE9   1
#define DEFEATED_ARCHER_PSFROUTE9   2

// VAR_SALESFORCETOWER_CONFERENCE_STATE 0x40F9 
#define DEFEATED_WHITNEY    1
#define POST_WOW_YOURE_STRONG   2
#define START_THE_GANGS_ALL_HERE 3
#define POST_THE_GANGS_ALL_HERE 4
#define PRE_WELCOME_TO_THE_WAR_ROOM 5
#define POST_WELCOME_TO_THE_WAR_ROOM    6
#define PRE_YOU_REALIZE_WERE_EVIL_RIGHT 7
#define POST_YOU_REALIZE_WERE_EVIL_RIGHT    8
#define START_FALSE_TIMELINE    9
#define TRUE_RAID_START 10
#define TRUE_RAID_SAVE_BIANCA   11

// VAR_LOMBARDSTREET_STATE 0x4056
#define NOT_SEEN_BIANCA_LOMBARD 0
#define SAVE_BIANCA_LOMBARD 1
#define DEFEATED_BIANCA_LOMBARD 2

//VAR_SALESFORCETOWER_PRODUCTION_STATE 0x40FD
#define HAS_NOT_STEPPED_INTO_SABRINA_ROOM 0
#define STEPPED_INTO_SABRINA_ROOM   1
#define POST_ALWAYS_WATCHING_WAZOWSKI   2

//VAR_DOGPATCH_STATE
#define PRE_HOW_DO_WE_GET_HOME 0
#define POST_HOW_DO_WE_GET_HOME 1

//VAR_BATTLE_8_STATE 0x4068
#define NOT_SEEN_ARCHER 1
#define SAVE_ARCHER_PAINTEDLADIES  2
#define DEFEATED_ARCHER_PAINTEDLADIES   3

//VAR_ALCATRAZ_STATE 0x409B
#define FIRST_ARRIVED_ALCATRAZ  1
#define BATTLED_MALVA   2
#define ARCHER_SUMMONED_ALCATRAZ    3
#define POST_ARRIVE_ALCATRAZ 4
#define PRE_YOU_REALIZE_THEYRE_EVIL_RIGHT  5
#define POST_YOU_REALIZE_THEYRE_EVIL_RIGHT  6
#define LAST_CHANCE_TRUE_TIMELINE_START 7
#define START_TRUE_TIMELINE 8
#define PRE_SPEECHSPEECH    9
#define POST_SPEECHSPEECH   10

//VAR_MUIRWOODS_STATE 0x406F
#define BIANCA_WAITING_MUIRWOODS    1
#define BIANCA_ENTERED_MUIRWOODS    2
#define MUIRWOODS_MAZE_COMPLETE 3
#define MET_SIEBOLD 4
#define FINISHED_SIEBOLD_PUZZLES    5
#define POST_HAVE_YOU_SEEN_THE_NEWS 6

//VAR_FERRY_STATE 0x40A8
#define FERRY_DEFAULT 0
#define FERRY_ALAMEDA_AVAILABLE 1
#define FERRY_ALCATRAZ_AVAILABLE    2
#define FERRY_TREASUREISLAND_AVAILABLE  3

//VAR_ALCATRAZ_EXHIBIT_STATE
#define ALCATRAZ_EXHIBIT_START  1
#define ALCATRAZ_EXHIBIT_FINISH 2
#define ALCATRAZ_EXHIBIT_REWARD 3
#define ALCATRAZ_EXHIBIT_COMPLETE   4

//VAR_FERRYBUILDING_STATE 0x4070
#define CHIEF_LEFT_WAR_ROOM 1
#define PLAYER_READY_SURVIVAL_CHANCE_BATTLE 2
#define SAVE_SURVIVAL_CHANCE_BATTLE  3
#define DEFEATED_SURVIVAL_CHANCE_BATTLE 4

//VAR_ALAMEDA_STATE 0x404E
#define HAS_NOT_ENCOUNTERED_ARCHER 0
#define SAVE_ARCHER_ALAMEDA 1
#define DEFEATED_ARCHER_ALAMEDA 2
#define START_SURVIVAL_CHANCE   3
#define POST_SURVIVAL_CHANCE    4
#define WHY_ARE_YOU_HELPING_THEM    5
#define SLEPT_AFTER_RAID    6
#define START_CHAMPIONSHIP_CLEAN_RAID   7
#define POST_EARTHQUAKE 8
#define START_EARTHQUAKE_RESCUE 9
#define POST_EARTHQUAKE_RESCUE  11
#define MEET_AT_PSFROUTE8   12
#define POST_THIS_ISNT_RANDOM 13

//VAR_NAVALBASE_STATE
#define NAVALBASE_RAID_NOT_STARTED 0
#define NAVALBASE_RAID_START 1
#define CHASE_GIOVANNI  2
#define SAVE_ARCHER_NAVALBASE   3
#define DEFEATED_ARCHER_NAVALBASE 4

//VAR_GROUP_OF_ASSHOLES_STATE
#define HAS_NOT_SEEN_GROUP_TEAMROCKET 0
#define SAVE_TEAMROCKET_FISHERMANSWHARF 1
#define PLAYER_HAS_DEFEATED_TEAM_ROCKET 2

//VAR_PSFROUTE63_STATE
#define PROTEST_NOTSTARTED  0
#define SAVE_TEAMROCKET_PSFROUTE63  1
#define DEFEATED_TEAMROCKET_PSFROUTE63  2

//VAR_FAINTED_FOG_STATE
#define NOT_DEFEATED_IN_FOG 0
#define DEFEATED_IN_FOG 1

//VAR_BERKELEY_STATE
#define SWAGBAG_2_COMPLETE  1
#define DEFEATED_MORTY  2
#define GOT_ALCATRAZ_TICKET 3

//VAR_HAIGHTASHBURY_STATE
#define PARADE_NOT_STARTED 0
#define PARADE_COMPLETE 1

//VAR_BEACH_BATTLE_STATE
#define NOT_SEEN_BIANCA_BEACH 0
#define SAVE_BIANCA_BEACH   1
#define POST_BEACH_BATTLE   2

//VAR_FORTPOINT_STATE
#define DEFEATED_CHUCK 1
#define MET_KOGA_OUTSIDE_GYM 2  

//VAR_KOGA_RAISON_DETRE_STATE
#define NOT_ENTERED_KOGA_HOUSE 0
#define MET_KOGA_KIDS   1
#define START_KOGA_WINE_SPEECH  2
#define POST_KOGA_WINE_SPEECH   3
#define POST_KOGA_RAISON_DETRE 4

//VAR_KOGA_MANSION_STATE
#define HAS_NOT_FINISHED_KOGA_RAISON 0
#define FINISHED_KOGA_RAISON 1

//VAR_WAIT_YOU_WENT_WHERE
#define PRE_WAITYOUWENTWHERE 0
#define POST_WAITYOUWENTWHERE 1

//VAR_CONSTRUCTION_STRIKE_STATE
#define STRIKE_NOT_STARTED 0
#define STRIKE_HAS_BEGUN    1
#define START_VS_GARBODOR   2
#define DEFEATED_GARBODOR   3
#define TEAM_ROCKET_ARRESTED 4

//VAR_INNER_CONSTRUCTION_SITE_STATE
#define PLAYER_LEFT_SIDE    1
#define PLAYER_RIGHT_SIDE   2

//VAR_GOLDENGATEBRIDGE_STATE 0x406C
#define CALLED_BY_BIANCA    1
#define POST_OFF_YOU_GO 2

//VAR_ROBINWILLIAMSTUNNEL_STATE 0x406D
#define BIANCA_INSIDE_TUNNEL 1
#define BIANCA_EXPLAINED_PUZZLE 2
#define PUZZLE_1_UNSOLVED   3
#define PUZZLE_1_SOLVED 4
#define PUZZLE_2_SOLVED 5
#define SIEBOLD_BOSS_DEFEATED   6

//VAR_MARIN_STATE 0x406E
#define ROBINWILLIAMSTUNNEL_PUZZLES_SOLVED 1
#define BIANCA_INVITED_AIRBNB   2

//VAR_CHASECENTER_TOURNAMENT_STATE 0x4072
#define NO_TOURNAMENT   0
#define PRE_BATTLE_1    1
#define PRE_BATTLE_2    2
#define PRE_BATTLE_3    3
#define PRE_BATTLE_4    4
#define PRE_BATTLE_5    5

//VAR_WAREHOUSE_RAVE_STATE
#define GOT_RAVE_MESSAGE    1
#define SAVE_KOGA_OAKLAND   2
#define DEFEATED_KOGA_OAKLAND   3
#define TOLD_ARCHER_ABOUT_KOGA  4

//VAR_HOW_DISAPPOINTING_STATE
#define MISSION_NOT_ASSIGNED    0
#define MISSION_ASSIGNED    1
#define GYM_RAID_STARTED    2
#define SAVED_BEFORE_ARIANA 3
#define DEFEATED_ARIANA_CHINATOWN   4
#define HOW_DISAPPOINTING_COMPLETE 5

//VAR_MANHUNT_STATE
#define NOT_ASSIGNED 0
#define ASSIGNED_FIND_GIOVANNI  1
#define GOT_MANHUNT_CLUE_1  2
#define GOT_MANHUNT_CLUE_2  3
#define GOT_MANHUNT_CLUE_3  4
#define GOT_MANHUNT_CLUE_4  5
#define DEFEATED_MANHUNT_GIOVANNI   6
#define MANHUNT_COMPLETE 7

//VAR_MASK_OFF_STATE 0x405C
#define NOT_ASSIGNED    0
#define ASSIGNED_MASK_OFF   1
#define GOT_MASK_OFF_CLUE_1  2
#define GOT_MASK_OFF_CLUE_2  3
#define GOT_MASK_OFF_CLUE_3  4
#define GOT_MASK_OFF_CLUE_4  5
#define GOT_MASK_OFF_CLUE_5  6
#define SAVE_GIOVANNI_LAKEMERRITT_TRUE  7
#define DEFEATED_MASK_OFF_GIOVANNI  8

//VAR_LETS_BURN_THIS_MOTHER_STATE
#define NOT_ASSIGNED 0
#define ASSIGNED_BURN_MOTHER    1
#define SAVE_ARCHER_ALCATRAZ    2
#define DEFEATED_ARCHER_ALCATRAZ    3
#define BURN_MOTHER_COMPLETE    4

//VAR_UNDERGROUNDLAB_STATE 0x4052
#define LAB_NOT_DISCOVERED  0
#define PLAYER_DISCOVERED_LAB   1
#define TEAMROCKET_DISCOVERED_LAB   2
#define DRASNA_UNLOCKED_DOOR    3
#define TEAM_INSIDE_LAB 4
#define FREED_LAB_POKEMON_1 5
#define FREED_LAB_POKEMON_2 6
#define SAVE_BEFORE_DYNAMAX 7
#define DEFEATED_DYNAMAX    8

//VAR_TOWER_RAID_STATE 0x4059
#define BROKEN_IN_SABRINA   1
#define SEARCHING_SABRINA_HOUSE 2
#define FOUND_SABRINA_WARP_DOOR 3
#define SABRINA_WARP_DOOR_UNLOCKED  4
#define TEAM_ENTERED_SALESFORCETOWER    5
#define SAVE_BIANCA_SALESFORCETOWER 6
#define DEFEATED_BIANCA_SALESFORCETOWER 7
#define STOPPED_BY_OAK 8
#define SAVE_ROSE_SALESFORCETOWER   9   
#define DEFEATED_ROSE_SALESFORCETOWER   10

//VAR_QUEST_CHINATOWN_TUNNELS
#define NEVER_SPOKEN_ELDER  0
#define SPOKEN_ELDER_FIRST_TIME  1
#define SENT_TO_FIND_RED_SCROLL 2
#define FOUND_RED_SCROLL    3

//VAR_FALKNER_STATE
//VAR_BUGSY_STATE
//VAR_WHITNEY_STATE
//VAR_MORTY_STATE
//VAR_CHUCK_STATE
//VAR_JASMINE_STATE
//VAR_PRYCE_STATE
//VAR_CLAIR_STATE
#define NO_BADGE             0
#define BATTLE_1_COMPLETE    1
#define QUEST_1_COMPLETE     2
#define QUEST_2_COMPLETE     3
#define BATTLE_2_COMPLETE    4

//VAR_CUTE_POKEMON_GUESS
//Number of times you have incorrectly brought a pokemon to the girl in the Quest Cute Pokemon
//resets after a subquest is completed


//VAR_QUEST_GARDENCLEANUPADVANCED
#define INCOMPLETE_GARDEN_QUEST 0
#define HAS_NOT_INTERACTED 1
#define SAVED_BEFORE_BATTLE 2
#define DEFEATED_GARDEN_BOSS 3

//VAR_QUEST_RESTOREMARIN
#define SAVE_BEFORE_LENORA_BATTLE 1
#define DEFEATED_LENORA 2

//VAR_QUEST_RESTORECHINATOWN
#define PRE_PEWFAT_INTO_GYM 0
#define POST_PEWFAT_INTO_GYM    1
#define FIND_CHINATOWN_LEADER   2
#define FOUND_CHINATOWN_LEADER  3
#define FIND_BLACKBELTS 4
#define FOUND_ALL_BLACKBELTS 11
#define RESTORECHINATOWN_COMPLETE   12
