gText_Birch_Welcome:: @ 82C897B
	.string "Sup!!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is a “POKéMON.”\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?\p"
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Which body would you like to use?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gNewGameAdventureIntro1::
    .string "Welcome to Pokémon San Fran!\n"
    .string "Before we get started...\n"
    .string "\n"
    .string "If you paid for this game,\n"
    .string "you have been scammed.\n\n"
    .string "We will never charge for the\n"
    .string "base version of the game.$"

gNewGameAdventureIntro2::
    .string "If you have any questions, comments\n"
    .string "concerns, or complaints,\n"
    .string "look at our website:\n"
    .string "\n"
    .string "http://pkmnsnfrn.io\n"
    .string "\n"
    .string "Join our community!\n"
    .string "http://discord.io/pkmnsnfrn$"

gNewGameAdventureIntro3::
    .string "Have fun!\n\n"
    .string "We worked really hard to make an\n"
    .string "experience that we hope\n"
    .string "all can enjoy!$"
