//PSF TODO Ask the player their favorite food. Will be used for You Look Tired cutscene
gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: 
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "$"

gText_Birch_AndYouAre:: 
	.string "And you are?\p"
	.string "$"

gText_Birch_BoyOrGirl:: 
	.string "Who do you want to look like?$"

gText_Birch_WhatCustom::
	.string "What would you like to customize?\n"
	.string "You can change these at a Salon.$"

gText_Birch_WhatHair::
	.string "What hair color would you like?$"

gText_Birch_WhatEyes::
	.string "What eye color would you like?$"

gText_Birch_WhatSkin::
	.string "What percent dark skin would you like?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gNewGameAdventureIntro1::
    .string "Welcome to Pokémon San Fran!\n"
    .string "Before we get started...\n"
    .string "\n"
    .string "If you paid for this game,\n"
    .string "you have been scammed.\n\n"
    .string "We will never charge for the\n"
    .string "base version of the game.$"

gNewGameAdventureIntro2::
    .string "If you have any questions, comments\n"
    .string "concerns, or complaints,\n"
    .string "look at our website:\n"
    .string "\n"
    .string "http://pkmnsnfrn.io\n"
    .string "\n"
    .string "Join our community!\n"
    .string "http://discord.io/pkmnsnfrn$"

gNewGameAdventureIntro3::
    .string "Have fun!\n\n"
    .string "We worked really hard to make an\n"
    .string "experience that we hope\n"
    .string "all can enjoy!$"
