	.align 2
/*
Script_StarterSelectScript::
    fadescreen 1
    lock
    msgbox gText_StarterSelectZoeyText1, MSGBOX_DEFAULT
    msgbox gText_StarterSelectZoeyText2, MSGBOX_DEFAULT
    fadescreen 0
    release
    end

gText_StarterSelectZoeyText1::
    .string "Almost packed and ready to go!\n"
    .string "I still can't believe I made it...$"

gText_StarterSelectZoeyText2::
    .string "But the rules say I can only bring\n"
    .string "one of you guys. Man, this sucks.\p"
    .string "I promise, once we're the Champion,\n"
    .string "we'll come back for the rest of you!\p"
    .string "But for now, it's all business...$"
gText_StarterSelectGameText1::
    .string "Due to the delicate ecosystem of\n"
    .string "the region, Trainers are permitted\l"
    .string "to bring one Pokémon from outside\l"
    .string "the region into the region with them.\p"
    .string "Please choose one Pokémon to accompany\n"
    .string "you on your adventure. You will not\l"
    .string "be able to access the others during\l"
    .string "your playthrough, so choose wisely.$"

gText_StarterSelectGameText2::
    .string "Please choose a Pokémon to bring\n"
    .string "with you to SanFran.$"


gText_StarterSelectPoliwhirlDesc::
    .string "{RIVAL} excels in the rain and\n"
    .string "gives plenty of options for Trainers.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectFletchhinderDesc::
    .string "{RIVAL} can provide offense or\n"
    .string "support with its high Speed.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectPetililDesc::
    .string "{RIVAL} best utilizies its high\n"
    .string "Special Attack in the sun.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectFlaaffyDesc::
    .string "{RIVAL} boasts a high Special Attack\n"
    .string "and diverse move pool.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectMareanieDesc::
    .string "{RIVAL} uses Defense and Special\n"
    .string "Defense to wear down foes.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectAronDesc::
    .string "{RIVAL} leverages its high Attack\n"
    .string "and Defense to provide physical support.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectSwinubDesc::
    .string "{RIVAL} hits most types for super-\n"
    .string "effective damage with its high attack.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectHattremDesc::
    .string "{RIVAL}'s high Special Attack and \n"
    .string "Special Defense makes it ideal for\l"
    .string "special support.\p"
    .string "Are you sure you want to choose {RIVAL}?$"

gText_StarterSelectPanchamDesc::
    .string "{RIVAL} makes up for low Speed\n"
    .string "with high Attack and unique typing.\p"
    .string "Are you sure you want to choose {RIVAL}?$"*/
