@ this is how you comment out a line for this shit

@ gText_SoPretty:: @ 8294295
@	.string " so pretty!$"

@ gMauvilleManText_ISoWantToGoOnAVacation:: @ 8294313
@	.string "I so want to go on a vacation.\n"
@	.string "Would you happen to know a nice place?$"

@ gText_SuperMonolougeText1::
@    .string "These are words that are being printed onto a screen.\n"
@    .string "Are you ready for a ride?$"
