name: Bug Report
description: bug report form
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - psf 
body:
  - type: markdown
    attributes:
      value: |
        ![Game Logo](https://i.imgur.com/pTHBBTq.png)

        Please use this form to report bugs for PSF. Thanks! 💕
  - type: input
    id: title 
    attributes:
      label: Bug Title 
      description: Give your bug a clear, concise title, like a tweet.
      placeholder: Cannot enter SOMA Gym
    validations:
      required: true 
  - type: textarea
    id: what-problem
    attributes:
      label: What is the problem?
      description: Please describe the problem you are experiencing. Be as descriptive as possible.
      placeholder: Even when the puzzle in the SOMA Gym is cleared, I cannot get to the Gym Leader to battle - the entrance is completely blocked off.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: What are the steps to produce your problem?
      description: Please give a step by step way to make the problem happen again.
      placeholder: Even when the puzzle in the SOMA Gym is cleared, I cannot get to the Gym Leader to battle - the entrance is completely blocked off.
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: What did you expect to happen instead?
      description: What should have happened?
      placeholder: After step 4, I expect that when I return, the path should be clear, but it is not.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
        Our lives become **much much easier** if you can provide (open links in a new tab!):

        * A gif or image of the issue happening. If you're able to capture that, you can upload them to [imgur](https://imgur.com/). Please post the resulting link in the next text field.

        * Your save file. This lets me figure out exactly what you did to get in the state you are in. It _should_ be the file called `pokeemerald.sav`, and you can upload it to [file.io](https://www.file.io). Please post the resulting link in the next text field.

        * You can see on how to perfect either of these tasks [here](https://i.imgur.com/XiWo17q.gif).

        ---
  - type: textarea
    id: other-info
    attributes:
      label: Any other info? 
      description: Any and all other information would be great, or links.
    validations:
      required: false
  - type: dropdown
    id: reporter
    attributes:
      label: Who are you?
      description: This matches your Discord username, which should be the last letter of first name & the last letter of your last name.
      options:
        - PSF
        - Aerun
        - Criminon
        - DS
        - ES
        - HN
        - JS
        - KW
        - LS
        - Miss Brie
        - MM
        - NN
        - NS
        - NZ
        - Patrick Afterplay
        - Rioluwott
        - XE
        - YN
        - Other
    validations:
      required: true
