Gldngtepark_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Gldngtepark_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE
	.byte 0

Gldngtepark_MapScripts_MAP_SCRIPT_ON_FRAME_TABLE:
	map_script_2 VAR_STORYLINE_STATE, 21, TheStrikeStrikesBack_PhoneCall_Dialogue
	.2byte 0


gText_Gldgtepark_PlaceholderOaklandFan::
	.string "I wish i could swear my signed\n"
	.string "Champion's cape, but I know i'll just\l"
	.string "get it dirty$"
