gLetter_Header::
	.string "Congratulations, {PLAYER}, you've been selected!\n"
	.string "$"
gLetter_Body::
	.string "We are pleased to inform you that your application to the YCOMBINATOR Kickstart Grant has been accepted. \n"
	.string "Our mission is to find the best and brightest young Pokémon Trainers and help accelerate their careers.\n"
	.string "As a YCOMBINATOR Kickstart Grant recipient, you will:\n"
	.string "Be flown to the SanFran region in September.\n"
	.string "Participate in the first season of the NEW YCOMBINATOR Sanctioned Pokémon League!\n"
	.string "Receive all the benefits of joining the YCOMBINATOR family, including housing, a stipend, and a toolkit of the best swag around.\n"
	.string "Please sign the attached documents and mail them to YCOMBINATOR Headquarters by April 17, 2019, to finalize your acceptance.\n"
	.string "$"
gLetter_Footer::
	.string "We're stoked to see what you can do!\n"
	.string "Sincerely,\n"
	.string "The YCOMBINATOR Family\n"
	.string "$"
