gLetter_Header::
	.string "Congratulations, {playerName}, you’ve been selected!\n"
	.string "$"
gLetter_Body::
	.string "We are pleased to inform you that your application to the YC Kickstart Grant has been accepted. \n"
	.string "Our mission is to find the best and brightest young Pokémon Trainers and help accelerate their careers.\n"
	.string "As a YC Kickstart Grant recipient, you will:\n"
	.string "Be flown to the SanFran region in September.\n"
	.string "Participate in the first season of the NEW YC Sanctioned Pokémon League!\n"
	.string "Receive all the benefits of joining the YC family, including housing, a stipend, and a toolkit of the best swag around.\n"
	.string "Please sign the attached documents and mail them to YC Headquarters by April 17, 2019, to finalize your acceptance.\n"
	.string "$"
gLetter_Footer::
	.string "We’re stoked to see what you can do!\n"
	.string "Sincerely,\n"
	.string "The YC Family\n"
	.string "$"