TwitterPost_RabiesOutbreak_Script::
	msgbox gText_Twitter_RabiesOutBreak_Dialogue, MSGBOX_DEFAULT
	startquest QUEST_RABIESOUTBREAK
	end


TwitterPost_BlueRobbery_Script::
	return


TwitterPost_IceCreamCrafting_Script::
	return


TwitterPost_VSDeoxys_Script::
	return


TwitterPost_ChinatownTunnels_Script::
	return


TwitterPost_FreshwaterEvolution_Script::
	return


TwitterPost_GemArtist_Script::
	return


TwitterPost_BetweenAStoneAndAHardPlace_Script::
	return


gText_Twitter_RabiesOutBreak_Dialogue::
	.string "My cousin told me there's a mass rabies\n"
	.string "outbreak in Bernalheights! Feral\l"
	.string "Glameow are attacking pets and people,\l"
	.string "accelerating the spread of the\l"
	.string "disease. He heard the ASPCA is gonna\l"
	.string "hook people up who can subdue or\l"
	.string "capture Glameow to reduce their impact\l"
	.string "on the local community. I'll be doing my\l"
	.string "part! hashtagDefeat10Glameow$"
